# Generated by Django 4.1.2 on 2022-10-19 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RoboChatTh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuser.friendsuser')),
                ('r_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robo.robofriend')),
            ],
        ),
        migrations.CreateModel(
            name='RoboChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatTime', models.DateTimeField()),
                ('ct_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robo.robochatth')),
            ],
        ),
    ]
