# Generated by Django 4.1.2 on 2022-12-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_remove_friendswith_a_f_uid_and_more'),
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboChat_Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuser.friendsuser')),
                ('r_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robo.robofriend')),
            ],
        ),
        migrations.RemoveField(
            model_name='robochat',
            name='ct_id',
        ),
        migrations.AddField(
            model_name='robochat',
            name='chat',
            field=models.TextField(default=0),
        ),
        migrations.DeleteModel(
            name='RoboChatTh',
        ),
        migrations.AddField(
            model_name='robochat',
            name='senderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgSender', to='robo.robochat_thread'),
        ),
        migrations.AddField(
            model_name='robochat',
            name='threadId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='robo.robochat_thread'),
        ),
    ]
