# Generated by Django 4.1.2 on 2022-12-13 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0002_robochat_thread_remove_robochat_ct_id_robochat_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robochat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='robochat',
            name='senderId',
        ),
        migrations.RemoveField(
            model_name='robochat_thread',
            name='r_id',
        ),
        migrations.AddField(
            model_name='robochat',
            name='robo_chat',
            field=models.TextField(default=None, max_length=10000000),
        ),
        migrations.AddField(
            model_name='robochat',
            name='user_chat',
            field=models.TextField(default=None, max_length=10000000),
        ),
        migrations.AlterField(
            model_name='robochat',
            name='chatTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='RoboFriend',
        ),
    ]
