# Generated by Django 4.1.2 on 2022-12-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendswith',
            name='a_f_uid',
        ),
        migrations.RemoveField(
            model_name='friendswith',
            name='b_f_uid',
        ),
        migrations.AddField(
            model_name='friendswith',
            name='a_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2', to='fuser.profile'),
        ),
        migrations.AddField(
            model_name='friendswith',
            name='b_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person1', to='fuser.profile'),
        ),
        migrations.AlterField(
            model_name='friendsuser',
            name='dOB',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='FriendsChat_Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fChat', models.TextField()),
                ('fChatTime', models.DateTimeField()),
                ('sender_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuser.friendswith')),
                ('threadId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thread', to='fuser.friendswith')),
            ],
        ),
    ]
